name: Build & Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build JAR
        run: ./gradlew --no-daemon clean bootJar

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/opt/myapp/"
          strip_components: 2
          # renombra el último jar a app.jar
          overwrite: true

      - name: Rename to app.jar and restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo chown app:app /opt/myapp/*.jar
            # tomá el último jar compilado y llamalo app.jar
            LATEST=$(ls -t /opt/myapp/*.jar | head -n1)
            sudo mv "$LATEST" /opt/myapp/app.jar
            sudo chown app:app /opt/myapp/app.jar
            sudo systemctl restart ${{ secrets.EC2_SERVICE }}
